ads/urls.py
from django.urls import path
from . import views

app_name = "ads"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("detail/<int:pk>/", views.AdDetailView.as_view(), name="detail"),
    path("profile/", views.ProfileView.as_view(), name="profile"),
    path("profile/create/", views.AdCreateView.as_view(), name="create"),
    path(
        "profile/update/<int:pk>/", views.AdUpdateView.as_view(),
        name="update"
    ),
    path("profile/delete/<int:pk>/", views.delete_ad, name="delete"),
    path(
        "profile/exchange/", views.ExchangeListView.as_view(),
        name="list_ex"
    ),
    path(
        "profile/exchange/ex_filter/<str:ex_filter>/",
        views.ExchangeListView.as_view(), name="ex_filter"
    ),
    path("searching/", views.SearchingView.as_view(), name="searching"),
    path(
        "filtering/<str:filtering>/", views.HomeView.as_view(),
        name="filtering"
    ),
    path("exchange/<int:pk>/", views.exchange_view, name="exchange"),

]

exchange/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("", include("ads.urls", namespace="ads")),
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include('ads.api_urls', namespace="api")),
]

ads/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse

class Category(models.Model):
    """
    Модель категорий товаров.
    """
    title = models.CharField(max_length=150)

    def __str__(self):
        return f"{self.title}"

class Ad(models.Model):
    """
    Модель товаров.
    """
    class Condition(models.TextChoices):
        NEW = "NEW", "Новый"
        USED = "USED", "Б/У"

    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    title = models.CharField(max_length=150)
    description = models.TextField()
    # image_url = models.ImageField(upload_to="images/", null=True, blank=True)
    category = models.ForeignKey('Category', on_delete=models.CASCADE)
    condition = models.CharField(choices=Condition, max_length=10)
    created_at = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse(
            "ads:detail",
            kwargs={"pk": self.id}
        )

    def __str__(self):
        return f"{self.title}"

class ExchangeProposal(models.Model):
    """
    Модель для обмена вещами.
    """
    class Status(models.TextChoices):
        WAIT = "WAIT", "Ожидает"
        ACCEPT = "ACCEPT", "Принято"
        REJECT = "REJECT", "Отклонено"


    ad_sender = models.ForeignKey(
        Ad, on_delete=models.CASCADE, related_name="sender", verbose_name="Отправитель"
    )
    ad_receiver = models.ForeignKey(
        Ad, on_delete=models.CASCADE, related_name="receiver"
    )
    comment = models.TextField()
    status = models.CharField(max_length=20, choices=Status, default=Status.WAIT)
    created_at = models.DateTimeField(auto_now_add=True)

ads/forms.py
from django import forms
from .models import Ad, ExchangeProposal

class CreateAdForm(forms.ModelForm):
    """
    Форма для создания объявления.
    """
    class Meta:
        model = Ad
        fields = ("category", "title", "description", "condition")

class ExchangeForm(forms.ModelForm):
    """
    Форма для запроса обмена.
    С фильтрациец товаров отправителя по пользователю.
    """
    class Meta:
        model = ExchangeProposal
        fields = ("ad_sender", "comment", "status")

    def __init__(self, *args, **kwargs):
        user = kwargs.pop("user")
        super().__init__(*args, **kwargs)
        self.fields["ad_sender"].queryset = Ad.objects.filter(user=user)

ads/views.py
from django.shortcuts import render, get_object_or_404
from django.core.exceptions import PermissionDenied
from django.views.generic import ListView, CreateView, DetailView, UpdateView
from .models import Ad, Category, ExchangeProposal
from .forms import CreateAdForm, ExchangeForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.db.models.functions import Lower

class HomeView(ListView):
    """
    Отображение списка объявлений с возможностью фильтрации.
    """
    template_name = "ads/home.html"
    queryset = Ad.objects.all()
    context_object_name = "ads"
    paginate_by = 10
    ordering = ("-created_at",)

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data()
        context["category"] = Category.objects.all()
        context["condition"] = Ad.Condition
        filtering = self.kwargs.get("filtering")
        if filtering in Ad.Condition:
            context["filtering"] = Ad.Condition[filtering].label
        else:
            context["filtering"] = filtering
        return context

    def get_queryset(self):
        if self.kwargs.get("filtering"):
            filter_name = self.kwargs["filtering"]
            try:
                filter_name = Ad.Condition[filter_name].label
            except KeyError:
                pass
            queryset = Ad.objects.filter(
                Q(category__title=filter_name) |
                Q(condition=filter_name)
            )
        else:
            queryset = super().get_queryset()
        return queryset

class ProfileView(LoginRequiredMixin, ListView):
    """
    Отображение всех объявлений пользователя.
    """
    template_name = "ads/profile.html"
    context_object_name = "ads"
    paginate_by = 10
    ordering = ["-created_at"]

    def get_queryset(self):
        user = self.request.user
        queryset = Ad.objects.filter(user=user)
        return queryset

class AdCreateView(LoginRequiredMixin, CreateView):
    """
    Создание объявления.
    """
    template_name = "ads/create.html"
    form_class = CreateAdForm

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class AdDetailView(DetailView):
    """
    Просмотр объявления отдельно.
    """
    queryset = Ad.objects.all()
    template_name = "ads/detail.html"
    context_object_name = "ad"

class AdUpdateView(LoginRequiredMixin, UpdateView):
    """
    Обновление объявления.
    """
    queryset = Ad.objects.all()
    template_name = "ads/update.html"
    form_class = CreateAdForm

    def get_object(self, queryset=None):
        obj = super().get_object()
        if obj.user != self.request.user:
            raise PermissionDenied
        return obj

def delete_ad(request, pk):
    """
    Уцдаление объявления.
    """
    ad = get_object_or_404(Ad, pk=pk)
    if request.user != ad.user:
        return render(request, "403.html")
    ad.delete()
    return render(
        request, "ads/delete.html", {"title": ad.title}
    )

class SearchingView(ListView):
    """
    Поиск по заголовку и в названии.
    Выдаёт список объявлений.
    """
    template_name = "ads/searching.html"
    context_object_name = "ads"
    paginate_by = 10
    ordering = ("-created_at",)

    def get_queryset(self):
        searching = self.request.GET.get("searching")
        queryset = Ad.objects.annotate(
            lower_title = Lower("title"),
            lower_description = Lower("description")
        ).filter(
            Q(lower_title__icontains=searching.lower()) |
            Q(lower_description__icontains=searching.lower())
        )
        return queryset

def exchange_view(request, pk):
    """
    Создание запроса на обмен.
    """
    ad = Ad.objects.get(pk=pk)
    user = request.user
    if request.method == "POST":
        form = ExchangeForm(request.POST, user=user)
        if form.is_valid():
            exchange = form.save(commit=False)
            exchange.ad_receiver = ad
            exchange.save()
            return render(request, "ads/exchange_success.html")
    else:
        form = ExchangeForm(user=user)
    return render(
        request, "ads/exchange.html",
        {"form": form, "ad": ad}
    )

class ExchangeListView(ListView):
    """
    Список всех запросов на обмен.
    """
    template_name = "ads/list_exchange.html"
    context_object_name = "ads"
    paginate_by = 10
    ordering = ("-created_at", )

    def get_queryset(self):
        user = self.request.user
        filt = self.kwargs.get("ex_filter")
        if filt:
            if filt == "sender":
                queryset = ExchangeProposal.objects.filter(
                    ad_sender__user=user
                )
            elif filt == "receiver":
                queryset = ExchangeProposal.objects.filter(
                    ad_receiver__user=user
                )
            else:
                queryset = ExchangeProposal.objects.filter(
                    Q(ad_sender__user=user) |
                    Q(ad_receiver__user=user)
                ).filter(status=filt)
        else:
            queryset = ExchangeProposal.objects.filter(
                Q(ad_sender__user=user) |
                Q(ad_receiver__user=user)
            )
        return queryset

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data()
        context["status"] = ExchangeProposal.Status
        return  context

templates/ads/create.html
{% extends "base.html" %}

{% block title %}Создать карточку товара{% endblock title %}

{% block content %}
  <form action="{% url "ads:create" %}" method="post">
    {{ form.as_p }}
    {% csrf_token %}
    <button type="submit">Создать</button>
  </form>
{% endblock content %}

templates/ads/delete.html
{% extends "base.html" %}

{% block title %}Удаление {{ ad }}{% endblock title %}

{% block content %}
  <hr>
    <p>{{ title }} успешно удалено</p>
{% endblock content %}

templates/ads/detail.html
{% extends "base.html" %}

{% block title %}{{ ad }}{% endblock title %}

{% block content %}
  <hr>
  <div>
    <p>{{ ad.category }}</p>
    <p>{{ ad.title }}</p>
    <p>{{ ad.description }}</p>
    <p>{{ ad.condition }}</p>
    <p>{{ ad.created_at }}</p>
  </div>
  <a href="{% url "ads:update" ad.pk %}">Редактировать товар</a>
  <a href="{% url "ads:delete" ad.pk %}">Удалить товар</a>
{% endblock content %}

templates/ads/exchange.html
{% extends "base.html" %}

{% block title %}{{ ad }}{% endblock title %}

{% block content %}
  <hr>
  <div>
    <p>{{ ad.category }}</p>
    <p>{{ ad.title }}</p>
    <p>{{ ad.description }}</p>
    <p>{{ ad.condition }}</p>
    <p>{{ ad.created_at }}</p>
  </div>
  <hr>
  <div>
    <form action="{% url 'ads:exchange' ad.pk %}" method="post">
      {{ form.as_p }}
      {% csrf_token %}
      <button>
        Отправить запрос
      </button>
    </form>
  </div>
{% endblock content %}

templates/ads/exchange_success.html
{% extends "base.html" %}

{% block title %}Список обменов{% endblock %}

{% block content %}
  <hr>
  <h1>Запрос на обмен успешно создан!</h1>
{% endblock %}

templates/ads/home.html
{% extends "base.html" %}

{% block title %}Главная страница{% endblock %}

{% block content %}
  <hr>
  <form action="{% url 'ads:searching' %}" method="get">
    <input name="searching" type="text" placeholder="Поиск">
  </form>
  <div>
  Фильтры по категориям:
  {% for cat in category %}
    <a href="{% url 'ads:filtering' cat %}">{{ cat.title }}</a>
  {% endfor %}
  Фильтры по состонию:
  {% for cond in condition %}
    <a href="{% url 'ads:filtering' cond %}">{{ cond.label }}</a>
  {% endfor %}
  </div>
  {% if filtering %}
    <h1>Фильтр по {{ filtering }}</h1>
  {% else %}
    <h1>Добро пожаловать на главную страницу!</h1>
  {% endif %}
  {% for ad in ads %}
    <div>
      <p>{{ ad.user }}</p>
      <p>{{ ad.category }}</p>
      <p><a href="{{ ad.get_absolute_url }}">{{ ad.title }}</a></p>
      <p>{{ ad.description }}</p>
      <p>{{ ad.condition }}</p>
      <p>{{ ad.created_at }}</p>
    </div>
    <hr>
  {% endfor %}
{% include "paginatot.html" %}
{% endblock %}

templates/ads/list_exchange.html
{% extends "base.html" %}

{% block title %}Список обменов{% endblock %}

{% block content %}
  <hr>
   Фильтры по статусу:
  {% for stat in status %}
    <a href="{% url 'ads:ex_filter' stat %}">{{ stat.label }}</a>
  {% endfor %}
  |
    <a href="{% url 'ads:ex_filter' "sender" %}">Мои запросы</a>
    <a href="{% url 'ads:ex_filter' "receiver" %}">Запросы ко мне</a>
  <hr>
  {% for ad in ads %}
    <div>
      <p>Запрос от: {{ ad.ad_sender }}</p>
      <p>Запрос на: {{ ad.ad_receiver }}</p>
      <p>Комментарий: {{ ad.comment }}</p>
      <p>Статус: {{ ad.status }}</p>
      <p>Дата создания: {{ ad.created_at }}</p>
    </div>
    <hr>
  {% endfor %}
{% include "paginatot.html" %}
{% endblock %}

templates/ads/profile.html
{% extends "base.html" %}

{% block title %}Профиль{% endblock title %}

{% block content %}
  <div>
    <a href="{% url "ads:create" %}">Выложить товар</a>
  </div>
  <hr>
  {% for ad in ads %}
    <div>
      <p>{{ ad.user }}</p>
      <p>{{ ad.category }}</p>
      <p><a href="{{ ad.get_absolute_url }}">{{ ad.title }}</a></p>
      <p>{{ ad.description }}</p>
      <p>{{ ad.condition }}</p>
      <p>{{ ad.created_at }}</p>
    </div>
    <hr>
  {% endfor %}

{% include "paginatot.html" %}
{% endblock content %}

templates/ads/search.html
{% extends "base.html" %}

{% block title %}Поиск{% endblock %}

{% block content %}
  <hr>
  <h1>Поиск</h1>

  {% for ad in ads %}
    <div>
      <p>{{ ad.user }}</p>
      <p>{{ ad.category }}</p>
      <p>{{ ad.title }}</p>
      <p>{{ ad.description }}</p>
      <p>{{ ad.condition }}</p>
      <p>{{ ad.created_at }}</p>
    </div>
    <hr>
  {% endfor %}
{% include "paginatot.html" %}
{% endblock %}

templates/ads/searching.html
{% extends "base.html" %}

{% block title %}Поиск{% endblock %}

{% block content %}
  <hr>
  <h1>Поиск</h1>

  {% for ad in ads %}
    <div>
      <p>{{ ad.user }}</p>
      <p>{{ ad.category }}</p>
      <p><a href="{{ ad.get_absolute_url }}">{{ ad.title }}</a></p>
      <p>{{ ad.description }}</p>
      <p>{{ ad.condition }}</p>
      <p>{{ ad.created_at }}</p>
    </div>
    <hr>
  {% endfor %}
{% include "paginatot.html" %}
{% endblock %}

templates/ads/update.html
{% extends "base.html" %}

{% block title %}Редактирование {{ ad }}{% endblock title %}

{% block content %}
  <form action="{% url "ads:create" %}" method="post">
    {{ form.as_p }}
    {% csrf_token %}
    <button type="submit">Обновить</button>
  </form>
{% endblock content %}