ads/urls.py
from django.urls import path
from . import views

app_name = "ads"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("detail/<int:pk>/", views.AdDetailView.as_view(), name="detail"),
    path("profile/", views.ProfileView.as_view(), name="profile"),
    path("profile/create/", views.AdCreateView.as_view(), name="create"),
    path(
        "profile/update/<int:pk>/", views.AdUpdateView.as_view(),
        name="update"
    ),
    path("profile/delete/<int:pk>/", views.delete_ad, name="delete"),
    path(
        "profile/exchange/", views.ExchangeListView.as_view(),
        name="list_ex"
    ),
    path(
        "profile/exchange/ex_filter/<str:ex_filter>/",
        views.ExchangeListView.as_view(), name="ex_filter"
    ),
    path("searching/", views.SearchingView.as_view(), name="searching"),
    path(
        "filtering/<str:filtering>/", views.HomeView.as_view(),
        name="filtering"
    ),
    path("exchange/<int:pk>/", views.exchange_view, name="exchange"),

]

exchange/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("", include("ads.urls", namespace="ads")),
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include('ads.api_urls', namespace="api")),
]

templates/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        Обмен вещами
        {% endblock title %}
    </title>
</head>
<body>
<header>
  <a href="{% url "ads:home" %}">Главная</a>
  {% if user.is_authenticated  %}
    <a href="{% url "ads:profile" %}">Профиль</a>
    <a href="{% url 'ads:list_ex' %}">Мои обмены</a>
    <form action="{% url "logout" %}" method="post" style="display: inline;">
    {% csrf_token %}
    <button type="submit">Выйти</button>
    </form>
  {% else %}
    <a href="{% url "login" %}">Войти</a>
  {% endif %}
</header>

{% block content %}
{% endblock content %}
</body>
</html>

templates/paginatot.html
<div>
  {% if page_obj.has_previous %}
    <a href="?page={{ page_obj.previous_page_number }}">Предыдущая страница</a>
  {% endif %}
    {{ page_obj.number }}
  {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}">Следующая страница</a>
  {% endif %}
</div>